apiVersion: v1
kind: Service
metadata:
  name: franklin
  labels:
    name: franklin
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    name: franklin
    version: "VERSION"
  type: LoadBalancer
